name: "Hello World"
env:
  GITHUB_TOKEN: ${{ secrets.github_token }}
  COMMIT_MSG: |
    <a commit message>
    skip-checks: true
runs:
  using: "node12"
  main: "lib/index.js"
runs: |
  git config user.email "<an email address>"
  git config user.name "<a name>"
  # Update origin with token
  git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
  # Checkout the branch so we can push back to it
  git checkout master
  git add .