name: "Hello World"
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: echo $(uname)
      - name: test
        run: |
          echo ${{ github.action_path }}
          echo ${{ github.action }}
          echo ${{ github.actor }}
          echo ${{ github.base_ref }}
          echo ${{ github.event }}
          echo ${{ github.event_name }}
          echo ${{ github.event_path }}
          echo ${{ github.head_ref }}
          echo ${{ github.job }}
          echo ${{ github.ref }}
          echo ${{ github.repository }}
          echo ${{ github.repository_owner }}
          echo ${{ github.run_id }}
          echo ${{ github.run_number }}
          echo ${{ github.sha }}
          echo ${{ github.workflow }}
          echo ${{ github.workspace }}
