name: multi-repo
on: [push]
  
jobs:
  repo1:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          ref: sample/repo1
          path: projects/repo1
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: projects/repo1/yarn.lock
      - name: setup
        run: |
          yarn install
          yarn build
        working-directory: projects/repo1
      - name: Store node_modules
        uses: actions/cache@v3
        env:
          cache-name: repo1-deps-cache
        with:
          path: projects/repo1/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo1/yarn.lock') }}
      - name: Store build result
        uses: actions/cache@v3
        env:
          cache-name: repo1-build-cache
        with:
          path: projects/repo1/lib
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo1/lib/index.js') }}
      - name: run script
        run: yarn start
  repo2:
    runs-on: ubuntu-latest
    steps:
      - name: checkout branch
        uses: actions/checkout@v3
        with:
          ref: sample/repo2
          path: projects/repo2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
          cache-dependency-path: projects/repo2/yarn.lock
      - name: setup
        run: |
          yarn install
          yarn build
        working-directory: projects/repo2
      - name: Store node_modules
        uses: actions/cache@v3
        env:
          cache-name: repo2-deps-cache
        with:
          path: projects/repo2/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo2/yarn.lock') }}
      - name: Store build result
        uses: actions/cache@v3
        env:
          cache-name: repo2-build-cache
        with:
          path: projects/repo2/lib
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo2/lib/index.js') }}
      - name: run script
        run: yarn start

  action:
    runs-on: ubuntu-latest
    needs: [repo1, repo2]
    steps:
      - name: checkout repo1 branch
        uses: actions/checkout@v3
        with:
          ref: sample/repo1
          path: projects/repo1
      - name: Restore node_modules
        uses: actions/cache@v3
        env:
          cache-name: repo1-deps-cache
        with:
          path: projects/repo1/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo1/yarn.lock') }}
      - name: Restore build result
        uses: actions/cache@v3
        env:
          cache-name: repo1-build-cache
        with:
          path: projects/repo1/lib
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo1/lib/index.js') }}

      - name: checkout branch
        uses: actions/checkout@v3
        with:
          ref: sample/repo2
          path: projects/repo2
      - name: Restore node_modules
        uses: actions/cache@v3
        env:
          cache-name: repo2-deps-cache
        with:
          path: projects/repo2/node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo2/yarn.lock') }}
      - name: Restore build result
        uses: actions/cache@v3
        env:
          cache-name: repo2-build-cache
        with:
          path: projects/repo2/lib
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('projects/repo2/lib/index.js') }}
      - name: check script
        run: |
          pwd
          echo ------repo1------
          cd projects/repo1
          yarn start

          echo ------repo2------
          cd ../repo2
          yarn start
        shell: bash
  
