name: Push CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Create PR
        uses: funivan/github-autopr@0.2.0
        with:
          args: .head_commit.message .repository.default_branch -v
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache Dependency
        uses: actions/cache@v1.0.0
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - run: yarn install
      - run: yarn build
      - run: yarn start
      - name: upload files
        uses: wei/curl@v1
        with:
          args: -X GET https://www.google.com
        env:
          CI: true
